name: Publish release (manual)
on:
  workflow_dispatch:
    inputs:
      tag:
        description: The tag to publish
        required: true
jobs:
  publish:
    name: Publish release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      discussions: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: refs/tags/${{ github.event.inputs.tag }}
      - name: Check if tag is SemVer
        id: check-tag
        run: |
          if [[ "${{ github.event.inputs.tag }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo is-semver=true >> $GITHUB_OUTPUT
            echo "Tag is SemVer"
          else
            echo "Tag is not SemVer"
          fi
      - name: Publish release
        uses: ghalactic/github-release-from-tag@main
        with:
          discussionCategory: ${{ steps.check-tag.outputs.is-semver == 'true' && 'Releases' || '' }}
